# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @rdname mvrt
#' @export
mvrt2 <- function(n, mu, S, df = 1L, max_norm = 2, max_iterations = 1000L) {
    .Call('_mvrt_mvrt2', PACKAGE = 'mvrt', n, mu, S, df, max_norm, max_iterations)
}

#' @rdname mvrt
#' @export
mvrt <- function(n, mu, S, df = 1L) {
    .Call('_mvrt_mvrt', PACKAGE = 'mvrt', n, mu, S, df)
}

