# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a multivariate t-distributed random matrix
#'
#' @param n Number of observations
#' @param mu Vector of sample means
#' @param S Covariance matrix
#' @param df Degrees of freedom
#' @export
mvrt <- function(n, mu, S, df = 1L) {
    .Call('_mvrt_mvrt', PACKAGE = 'mvrt', n, mu, S, df)
}

